### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [extpankov/lab2#1]
1. Ошибки при операциях с двоичными числами и в формате вывода ответа у них. Как там вообще 2 появилась то???
![изображение](https://github.com/extpankov/lab2/assets/36138085/5270cfbb-5b23-480a-bac7-7bc33e0ffa72)
![изображение](https://github.com/extpankov/lab2/assets/36138085/c2de76e9-2188-43ef-add7-f24b2dfa8d4d)
2. Внимательно читаем задание лабораторной. Такие операции не должны выполнятся, должна выводиться ошибка.
![изображение](https://github.com/extpankov/lab2/assets/36138085/eb8ac07d-b44d-4fcb-ba3b-0ecfa6567c60)
![изображение](https://github.com/extpankov/lab2/assets/36138085/45fe36ec-dda6-455f-af21-deea3de47ab3)
![изображение](https://github.com/extpankov/lab2/assets/36138085/7f73c5fe-f813-4b83-988d-ec7b424c48c8)

**Comment by extpankov** [comment]
Добрый вечер, спасибо. 
Изменения добавлены.

**Comment by rredbird66** [comment]
Всё ок.
Лабораторная работа 2 зачтена.
